@file:JvmName("ThemeBubbleOverride")

package io.relimus.flatgram.theme.builtin

import androidx.annotation.ColorInt
import me.vkryl.annotation.Autogenerated
import io.relimus.flatgram.theme.ColorId
import io.relimus.flatgram.theme.ThemeDelegate
import io.relimus.flatgram.theme.ThemeId
import io.relimus.flatgram.theme.ThemeSet

@Autogenerated open class ThemeBubbleOverride (@ThemeId id: Int, @ThemeId bubbleThemeId: Int) : ThemeDefault(id) {
  private val bubbleTheme: ThemeDelegate = ThemeSet.getBuiltinTheme(bubbleThemeId)
  
  @ColorInt override fun getColor (colorId: Int) = when (colorId) {
    ColorId.bubbleOut_background,
    ColorId.bubbleOut_time,
    ColorId.bubbleOut_progress,
    ColorId.bubbleOut_text,
    ColorId.bubbleOut_textLink,
    ColorId.bubbleOut_textLinkPressHighlight,
    ColorId.bubbleOut_outline,
    ColorId.bubbleOut_separator,
    ColorId.bubbleOut_pressed,
    ColorId.bubbleOut_chatVerticalLine,
    ColorId.bubbleOut_chatNeutralFillingContent,
    ColorId.bubbleOut_chatCorrectFilling,
    ColorId.bubbleOut_chatCorrectFillingContent,
    ColorId.bubbleOut_chatCorrectChosenFilling,
    ColorId.bubbleOut_chatCorrectChosenFillingContent,
    ColorId.bubbleOut_chatNegativeFilling,
    ColorId.bubbleOut_chatNegativeFillingContent,
    ColorId.bubbleOut_inlineText,
    ColorId.bubbleOut_inlineOutline,
    ColorId.bubbleOut_inlineIcon,
    ColorId.bubbleOut_waveformActive,
    ColorId.bubbleOut_waveformInactive,
    ColorId.bubbleOut_file,
    ColorId.bubbleOut_fileContent,
    ColorId.bubbleOut_ticks,
    ColorId.bubbleOut_ticksRead,
    ColorId.bubbleOut_messageAuthor,
    ColorId.bubbleOut_messageAuthorPsa,
    ColorId.bubbleOut_fillingActive,
    ColorId.bubbleOut_fillingActiveContent,
    ColorId.bubbleOut_fillingPositive,
    ColorId.bubbleOut_fillingPositiveContent,
    ColorId.bubbleOut_fillingPositive_overlay,
    ColorId.bubbleOut_fillingPositiveContent_overlay,
    ColorId.bubbleOut_blockQuoteText,
    ColorId.bubbleOut_blockQuoteLine -> bubbleTheme.getColor(colorId)
    else -> super.getColor(colorId)
  }
}