@file:JvmName("ThemePink")

package io.relimus.flatgram.theme.builtin

import androidx.annotation.ColorInt
import me.vkryl.annotation.Autogenerated
import io.relimus.flatgram.theme.ColorId
import io.relimus.flatgram.theme.ColorIdTinted
import io.relimus.flatgram.theme.ThemeId
import io.relimus.flatgram.theme.PropertyId

@Autogenerated class ThemePink : ThemeDefault(ThemeId.PINK) {
  override fun getProperty (@PropertyId propertyId: Int): Float = when (propertyId) {
    PropertyId.PARENT_THEME ->
      1.0f
    else -> super.getProperty(propertyId)
  }

  @ColorInt override fun getColor (@ColorIdTinted colorId: Int): Int = when (colorId) {
    ColorId.badge, ColorId.bubbleIn_progress, ColorId.bubbleIn_textLink, ColorId.bubbleOut_chatCorrectChosenFilling, ColorId.bubbleOut_chatCorrectFilling, ColorId.bubbleOut_chatVerticalLine, ColorId.bubbleOut_inlineOutline, ColorId.bubbleOut_textLink, ColorId.bubbleOut_ticks, ColorId.bubbleOut_ticksRead, ColorId.bubbleOut_waveformActive, ColorId.chatListVerify, ColorId.circleButtonActive, ColorId.circleButtonRegular, ColorId.circleButtonTheme, ColorId.headerBarCallActive, ColorId.inlineOutline, ColorId.inputActive, ColorId.iv_textLink, ColorId.iv_textMarkedLink, ColorId.messageCorrectChosenFilling, ColorId.messageCorrectFilling, ColorId.messageSwipeBackground, ColorId.messageVerticalLine, ColorId.progress, ColorId.seekDone, ColorId.sliderActive, ColorId.snackbarUpdate, ColorId.textLink, ColorId.textNeutral, ColorId.ticks, ColorId.ticksRead, ColorId.togglerActive, ColorId.unreadText, ColorId.waveformActive, ColorId.bubbleOut_fillingPositive, ColorId.bubbleIn_fillingPositive, ColorId.bubbleIn_fillingPositive_overlay, ColorId.bubbleOut_fillingPositive_overlay, ColorId.fillingPositive ->
      -1294214 // 0xffec407a
    ColorId.bubbleIn_textLinkPressHighlight, ColorId.bubbleOut_textLinkPressHighlight, ColorId.iv_textLinkPressHighlight, ColorId.iv_textMarkedLinkPressHighlight, ColorId.textLinkPressHighlight, ColorId.tooltip_textLinkPressHighlight ->
      1089224826 // 0x40ec407a
    ColorId.bubbleOut_background, ColorId.unread ->
      -203540 // 0xfffce4ec
    ColorId.bubbleOut_file, ColorId.controlActive, ColorId.file, ColorId.playerButtonActive, ColorId.profileSectionActive, ColorId.profileSectionActiveContent, ColorId.promo, ColorId.textSearchQueryHighlight, ColorId.tooltip_textLink, ColorId.avatarArchive, ColorId.avatarSavedMessages, ColorId.avatarSavedMessages_big, ColorId.avatarReplies, ColorId.avatarReplies_big ->
      -1023342 // 0xfff06292
    ColorId.bubbleOut_inlineIcon, ColorId.bubbleOut_inlineText, ColorId.bubbleOut_progress, ColorId.bubbleOut_separator, ColorId.bubbleOut_time, ColorId.chatSendButton, ColorId.checkActive, ColorId.headerBackground, ColorId.iconActive, ColorId.inlineIcon, ColorId.inlineText, ColorId.notification, ColorId.notificationLink, ColorId.notificationPlayer, ColorId.passcode ->
      -1499549 // 0xffe91e63
    ColorId.bubbleOut_messageAuthor, ColorId.chatListAction, ColorId.messageAuthor, ColorId.online ->
      -2614432 // 0xffd81b60
    ColorId.bubbleOut_waveformInactive, ColorId.textSelectionHighlight, ColorId.togglerActiveBackground, ColorId.waveformInactive ->
      -476208 // 0xfff8bbd0
    ColorId.messageSelection ->
      283918458 // 0x10ec407a
    ColorId.headerBadgeFailed ->
      -11513 // 0xffffd307
    ColorId.seekReady ->
      -272156 // 0xfffbd8e4
    ColorId.bubble_messageSelection, ColorId.bubble_messageSelectionNoWallpaper ->
      870915683 // 0x33e91e63
    ColorId.bubbleOut_fillingActive ->
      450450560 // 0x1ad95480
    else -> super.getColor(colorId)
  }
}