@file:JvmName("ThemeRed")

package io.relimus.flatgram.theme.builtin

import androidx.annotation.ColorInt
import me.vkryl.annotation.Autogenerated
import io.relimus.flatgram.theme.ColorId
import io.relimus.flatgram.theme.ColorIdTinted
import io.relimus.flatgram.theme.ThemeId
import io.relimus.flatgram.theme.PropertyId

@Autogenerated class ThemeRed : ThemeDefault(ThemeId.RED) {
  override fun getProperty (@PropertyId propertyId: Int): Float = when (propertyId) {
    PropertyId.PARENT_THEME ->
      1.0f
    else -> super.getProperty(propertyId)
  }

  @ColorInt override fun getColor (@ColorIdTinted colorId: Int): Int = when (colorId) {
    ColorId.badge, ColorId.bubbleIn_progress, ColorId.bubbleOut_file, ColorId.bubbleOut_waveformActive, ColorId.chatListAction, ColorId.chatSendButton, ColorId.circleButtonActive, ColorId.circleButtonRegular, ColorId.circleButtonTheme, ColorId.controlActive, ColorId.file, ColorId.fileRed, ColorId.headerBarCallActive, ColorId.playerButtonActive, ColorId.profileSectionActive, ColorId.progress, ColorId.promo, ColorId.snackbarUpdate, ColorId.textSearchQueryHighlight, ColorId.waveformActive, ColorId.tooltip_textLink, ColorId.avatarArchive, ColorId.avatarSavedMessages, ColorId.avatarSavedMessages_big, ColorId.avatarReplies, ColorId.avatarReplies_big, ColorId.bubbleOut_fillingPositive, ColorId.bubbleIn_fillingPositive, ColorId.bubbleIn_fillingPositive_overlay, ColorId.bubbleOut_fillingPositive_overlay, ColorId.fillingPositive ->
      -769226 // 0xfff44336
    ColorId.bubbleIn_textLink, ColorId.bubbleOut_chatCorrectChosenFilling, ColorId.bubbleOut_chatCorrectFilling, ColorId.bubbleOut_chatVerticalLine, ColorId.bubbleOut_textLink, ColorId.chatListVerify, ColorId.inputActive, ColorId.iv_textLink, ColorId.iv_textMarkedLink, ColorId.messageCorrectChosenFilling, ColorId.messageCorrectFilling, ColorId.messageVerticalLine, ColorId.seekDone, ColorId.sliderActive, ColorId.textLink, ColorId.textNeutral ->
      -1092784 // 0xffef5350
    ColorId.bubbleIn_textLinkPressHighlight, ColorId.bubbleOut_textLinkPressHighlight, ColorId.iv_textLinkPressHighlight, ColorId.iv_textMarkedLinkPressHighlight, ColorId.textLinkPressHighlight, ColorId.tooltip_textLinkPressHighlight ->
      1089426256 // 0x40ef5350
    ColorId.bubbleOut_background ->
      -72733 // 0xfffee3e3
    ColorId.bubbleOut_inlineIcon, ColorId.inlineIcon, ColorId.messageSwipeBackground ->
      -2937041 // 0xffd32f2f
    ColorId.bubbleOut_inlineOutline, ColorId.bubbleOut_inlineText, ColorId.bubbleOut_messageAuthor, ColorId.checkActive, ColorId.inlineOutline, ColorId.inlineText, ColorId.messageAuthor, ColorId.online, ColorId.profileSectionActiveContent, ColorId.togglerActive, ColorId.unreadText ->
      -1754827 // 0xffe53935
    ColorId.bubbleOut_progress, ColorId.bubbleOut_separator, ColorId.bubbleOut_time ->
      -4292479 // 0xffbe8081
    ColorId.bubbleOut_ticks, ColorId.bubbleOut_ticksRead, ColorId.iconActive, ColorId.ticks, ColorId.ticksRead ->
      -1427147 // 0xffea3935
    ColorId.bubbleOut_waveformInactive ->
      -344638 // 0xfffabdc2
    ColorId.headerBadgeFailed ->
      -11513 // 0xffffd307
    ColorId.headerBackground, ColorId.notification, ColorId.notificationLink, ColorId.notificationPlayer, ColorId.passcode ->
      -3790808 // 0xffc62828
    ColorId.messageSelection ->
      280435740 // 0x10b71c1c
    ColorId.seekReady ->
      -273197 // 0xfffbd4d3
    ColorId.textNegative ->
      -4776932 // 0xffb71c1c
    ColorId.textSelectionHighlight ->
      -742228 // 0xfff4acac
    ColorId.togglerActiveBackground ->
      -1074534 // 0xffef9a9a
    ColorId.unread ->
      -5138 // 0xffffebee
    ColorId.waveformInactive ->
      -12846 // 0xffffcdd2
    ColorId.bubble_messageSelection, ColorId.bubble_messageSelectionNoWallpaper ->
      870660405 // 0x33e53935
    ColorId.bubbleOut_fillingActive ->
      450052160 // 0x1ad34040
    else -> super.getColor(colorId)
  }
}