@file:JvmName("ThemeCyan")

package io.relimus.flatgram.theme.builtin

import androidx.annotation.ColorInt
import me.vkryl.annotation.Autogenerated
import io.relimus.flatgram.theme.ColorId
import io.relimus.flatgram.theme.ColorIdTinted
import io.relimus.flatgram.theme.ThemeId
import io.relimus.flatgram.theme.PropertyId

@Autogenerated class ThemeCyan : ThemeDefault(ThemeId.CYAN) {
  override fun getProperty (@PropertyId propertyId: Int): Float = when (propertyId) {
    PropertyId.PARENT_THEME ->
      1.0f
    else -> super.getProperty(propertyId)
  }

  @ColorInt override fun getColor (@ColorIdTinted colorId: Int): Int = when (colorId) {
    ColorId.badge, ColorId.fillingPositive, ColorId.bubbleOut_inlineOutline, ColorId.bubbleOut_fillingPositive, ColorId.bubbleOut_fillingPositive_overlay, ColorId.bubbleIn_fillingPositive, ColorId.bubbleIn_fillingPositive_overlay, ColorId.chatListAction, ColorId.chatListVerify, ColorId.circleButtonActive, ColorId.circleButtonRegular, ColorId.circleButtonTheme, ColorId.headerBarCallActive, ColorId.inlineOutline, ColorId.inputActive, ColorId.profileSectionActiveContent, ColorId.seekDone, ColorId.sliderActive, ColorId.snackbarUpdate ->
      -14235942 // 0xff26c6da
    ColorId.bubbleIn_progress, ColorId.bubbleIn_textLink, ColorId.bubbleOut_chatCorrectChosenFilling, ColorId.bubbleOut_chatCorrectFilling, ColorId.bubbleOut_chatVerticalLine, ColorId.bubbleOut_inlineIcon, ColorId.bubbleOut_inlineText, ColorId.bubbleOut_messageAuthor, ColorId.bubbleOut_textLink, ColorId.bubbleOut_ticks, ColorId.bubbleOut_ticksRead, ColorId.bubbleOut_waveformActive, ColorId.checkActive, ColorId.iconActive, ColorId.inlineIcon, ColorId.inlineText, ColorId.iv_textLink, ColorId.iv_textMarkedLink, ColorId.messageAuthor, ColorId.messageCorrectChosenFilling, ColorId.messageCorrectFilling, ColorId.messageSwipeBackground, ColorId.messageVerticalLine, ColorId.progress, ColorId.textLink, ColorId.textNeutral, ColorId.ticks, ColorId.ticksRead, ColorId.togglerActive, ColorId.unreadText, ColorId.waveformActive ->
      -16728876 // 0xff00bcd4
    ColorId.bubbleIn_textLinkPressHighlight, ColorId.bubbleOut_textLinkPressHighlight, ColorId.iv_textLinkPressHighlight, ColorId.iv_textMarkedLinkPressHighlight, ColorId.textLinkPressHighlight, ColorId.tooltip_textLinkPressHighlight ->
      1073790164 // 0x4000bcd4
    ColorId.bubbleOut_background, ColorId.textSelectionHighlight, ColorId.unread ->
      -2033670 // 0xffe0f7fa
    ColorId.bubbleOut_file, ColorId.controlActive, ColorId.file, ColorId.playerButtonActive, ColorId.profileSectionActive, ColorId.promo, ColorId.textSearchQueryHighlight, ColorId.tooltip_textLink, ColorId.avatarArchive, ColorId.avatarSavedMessages, ColorId.avatarSavedMessages_big, ColorId.avatarReplies, ColorId.avatarReplies_big ->
      -11677471 // 0xff4dd0e1
    ColorId.bubbleOut_waveformInactive, ColorId.togglerActiveBackground, ColorId.waveformInactive ->
      -5051406 // 0xffb2ebf2
    ColorId.chatSendButton, ColorId.online ->
      -16732991 // 0xff00acc1
    ColorId.headerBadge ->
      -16253130 // 0xff07ff36
    ColorId.headerBackground, ColorId.notification, ColorId.notificationLink, ColorId.notificationPlayer, ColorId.passcode ->
      -16738393 // 0xff0097a7
    ColorId.messageSelection ->
      273535201 // 0x104dd0e1
    ColorId.seekReady ->
      -3542795 // 0xffc9f0f5
    ColorId.bubble_messageSelection, ColorId.bubble_messageSelectionNoWallpaper ->
      855686356 // 0x3300bcd4
    ColorId.bubbleOut_fillingActive ->
      644860098 // 0x266fc8c2
    else -> super.getColor(colorId)
  }
}