@file:JvmName("ThemeNightBlue")

package io.relimus.flatgram.theme.builtin

import androidx.annotation.ColorInt
import me.vkryl.annotation.Autogenerated
import io.relimus.flatgram.theme.ColorId
import io.relimus.flatgram.theme.ThemeId
import io.relimus.flatgram.theme.PropertyId

@Autogenerated class ThemeNightBlue : ThemeDefault(ThemeId.NIGHT_BLUE) {
  override fun getProperty (@PropertyId propertyId: Int): Float = when (propertyId) {
    PropertyId.DARK, PropertyId.PARENT_THEME, PropertyId.SHADOW_DEPTH, PropertyId.WALLPAPER_USAGE_ID ->
      1.0f
    else -> super.getProperty(propertyId)
  }

  @ColorInt override fun getColor (@ColorId colorId: Int): Int = when (colorId) {
    ColorId.attachContact, ColorId.attachFile, ColorId.attachInlineBot, ColorId.attachLocation, ColorId.attachPhoto, ColorId.bubble_mediaReply_noWallpaper, ColorId.bubble_unread_noWallpaper, ColorId.bubbleIn_background, ColorId.circleButtonChat, ColorId.circleButtonOverlay, ColorId.filling, ColorId.overlayFilling, ColorId.unread ->
      -14932173 // 0xff1c2733
    ColorId.background, ColorId.chatBackground, ColorId.chatKeyboard, ColorId.iv_chatLinkBackground, ColorId.iv_preBlockBackground, ColorId.iv_textCodeBackground, ColorId.iv_textCodeBackgroundPressed ->
      -15393498 // 0xff151d26
    ColorId.background_icon, ColorId.badgeMuted, ColorId.bubbleIn_time, ColorId.circleButtonChatIcon, ColorId.circleButtonOverlayIcon, ColorId.icon, ColorId.iv_caption, ColorId.iv_icon, ColorId.iv_pageAuthor, ColorId.iv_pageFooter, ColorId.textLight, ColorId.textPlaceholder, ColorId.headerBadgeMuted ->
      -8548712 // 0xff7d8e98
    ColorId.background_text, ColorId.background_textLight ->
      -8746606 // 0xff7a8992
    ColorId.badge, ColorId.bubbleOut_ticksRead, ColorId.chatListAction, ColorId.chatListVerify, ColorId.checkActive, ColorId.iconActive, ColorId.seekDone, ColorId.sliderActive, ColorId.ticks, ColorId.ticksRead, ColorId.headerBadge ->
      -10901278 // 0xff59a8e2
    ColorId.badgeMutedText ->
      -16777216 // 0xff000000
    ColorId.bubble_button_noWallpaper, ColorId.bubble_buttonRipple_noWallpaper ->
      805306368 // 0x30000000
    ColorId.bubble_chatSeparator, ColorId.bubbleIn_outline, ColorId.bubbleIn_separator, ColorId.bubbleOut_outline, ColorId.chatSeparator, ColorId.inputInactive, ColorId.iv_separator, ColorId.separator, ColorId.shareSeparator ->
      -15722722 // 0xff10171e
    ColorId.bubble_date, ColorId.bubble_date_noWallpaper, ColorId.bubble_overlay ->
      1712659750 // 0x66151d26
    ColorId.bubble_messageSelection, ColorId.bubbleIn_pressed ->
      536870912 // 0x20000000
    ColorId.bubble_messageSelectionNoWallpaper ->
      704643072 // 0x2a000000
    ColorId.bubbleIn_progress, ColorId.chatSendButton, ColorId.controlActive, ColorId.inputActive, ColorId.profileSectionActive, ColorId.profileSectionActiveContent, ColorId.progress, ColorId.promo, ColorId.textNeutral, ColorId.textSearchQueryHighlight, ColorId.togglerActive, ColorId.togglerPositive ->
      -10170627 // 0xff64cefd
    ColorId.bubbleIn_text, ColorId.bubbleOut_text, ColorId.drawerText, ColorId.headerButtonIcon, ColorId.headerLightIcon, ColorId.headerLightText, ColorId.introSectionActive, ColorId.iv_blockQuoteLine, ColorId.iv_header, ColorId.iv_pageTitle, ColorId.iv_text, ColorId.iv_textCode, ColorId.iv_textMarked, ColorId.iv_textReference, ColorId.playerButton, ColorId.text, ColorId.themeBlackWhite, ColorId.unreadText, ColorId.fillingActiveContent, ColorId.bubbleIn_fillingActiveContent, ColorId.bubbleOut_fillingActiveContent ->
      -1 // 0xffffffff
    ColorId.bubbleIn_textLink, ColorId.circleButtonActive, ColorId.circleButtonRegular, ColorId.circleButtonTheme, ColorId.headerButton, ColorId.iv_textLink, ColorId.iv_textMarkedLink, ColorId.messageAuthor, ColorId.notificationLink, ColorId.snackbarUpdate, ColorId.textLink ->
      -10376735 // 0xff61a9e1
    ColorId.bubbleIn_textLinkPressHighlight, ColorId.iv_textLinkPressHighlight, ColorId.textLinkPressHighlight ->
      1147251169 // 0x4461a9e1
    ColorId.bubbleOut_background, ColorId.messageSwipeBackground ->
      -12227949 // 0xff456a93
    ColorId.bubbleOut_chatCorrectChosenFilling, ColorId.bubbleOut_chatCorrectFilling, ColorId.bubbleOut_chatVerticalLine, ColorId.bubbleOut_inlineIcon, ColorId.bubbleOut_inlineOutline, ColorId.bubbleOut_inlineText, ColorId.bubbleOut_messageAuthor, ColorId.bubbleOut_textLink, ColorId.bubbleOut_ticks, ColorId.messageCorrectChosenFilling, ColorId.messageCorrectFilling ->
      -7943425 // 0xff86caff
    ColorId.bubbleOut_file, ColorId.bubbleOut_waveformActive, ColorId.file, ColorId.bubbleIn_fillingPositive, ColorId.bubbleIn_fillingPositive_overlay, ColorId.bubbleOut_fillingPositive, ColorId.bubbleOut_fillingPositive_overlay ->
      -10376991 // 0xff61a8e1
    ColorId.bubbleOut_progress, ColorId.bubbleOut_separator, ColorId.bubbleOut_time ->
      -7229496 // 0xff91afc8
    ColorId.bubbleOut_textLinkPressHighlight ->
      1082575615 // 0x4086caff
    ColorId.bubbleOut_waveformInactive, ColorId.waveformInactive ->
      -9727571 // 0xff6b91ad
    ColorId.chatKeyboardButton ->
      -14606047 // 0xff212121
    ColorId.chatListIcon, ColorId.chatListMute, ColorId.togglerInactive ->
      -8745319 // 0xff7a8e99
    ColorId.controlInactive, ColorId.sliderInactive, ColorId.togglerInactiveBackground ->
      -11970202 // 0xff495966
    ColorId.drawer, ColorId.statusBar ->
      1073741824 // 0x40000000
    ColorId.fileAttach, ColorId.playerCoverPlaceholder ->
      -15327448 // 0xff161f28
    ColorId.fillingPressed ->
      -14671840 // 0xff202020
    ColorId.headerBackground, ColorId.headerLightBackground, ColorId.notification, ColorId.notificationPlayer, ColorId.passcode ->
      -14537156 // 0xff222e3c
    ColorId.headerPlaceholder ->
      285212671 // 0x10ffffff
    ColorId.iconLight ->
      -11248797 // 0xff545b63
    ColorId.inlineIcon, ColorId.inlineOutline, ColorId.inlineText ->
      -10508068 // 0xff5fa8dc
    ColorId.introSection ->
      -8289919 // 0xff818181
    ColorId.iv_blockQuote ->
      -197380 // 0xfffcfcfc
    ColorId.iv_pageSubtitle ->
      -8285540 // 0xff81929c
    ColorId.iv_pullQuote ->
      -394759 // 0xfff9f9f9
    ColorId.iv_textReferenceBackground ->
      720564978 // 0x2af2f2f2
    ColorId.iv_textReferenceBackgroundPressed ->
      820044000 // 0x30e0e0e0
    ColorId.iv_textReferenceOutline ->
      1157627903 // 0x44ffffff
    ColorId.iv_textReferenceOutlinePressed ->
      553648127 // 0x20ffffff
    ColorId.messageSelection ->
      274835937 // 0x1061a9e1
    ColorId.messageVerticalLine ->
      -11301187 // 0xff538ebd
    ColorId.nameInactive, ColorId.lineInactive, ColorId.themeNightBlack ->
      -9803158 // 0xff6a6a6a
    ColorId.notificationSecure, ColorId.textSecure ->
      -8854914 // 0xff78e27e
    ColorId.placeholder ->
      218103807 // 0x0cffffff
    ColorId.playerButtonActive ->
      -10967328 // 0xff58a6e0
    ColorId.playerCoverIcon ->
      -9865086 // 0xff697882
    ColorId.previewBackground ->
      1879048192 // 0x70000000
    ColorId.seekEmpty ->
      -15525084 // 0xff131b24
    ColorId.seekReady ->
      -14008754 // 0xff2a3e4e
    ColorId.textSelectionHighlight ->
      -13285539 // 0xff35475d
    ColorId.togglerActiveBackground, ColorId.togglerPositiveBackground ->
      -12487273 // 0xff417597
    ColorId.tooltip ->
      -301989888 // 0xee000000
    ColorId.tooltip_outline ->
      541420179 // 0x20456a93
    ColorId.waveformActive ->
      -14332834 // 0xff254c5e
    ColorId.fillingActive, ColorId.bubbleIn_fillingActive ->
      645762712 // 0x267d8e98
    ColorId.bubbleOut_fillingActive ->
      647081928 // 0x2691afc8
    ColorId.blockQuoteText, ColorId.blockQuoteLine ->
      -5981755 // 0xffa4b9c5
    ColorId.bubbleIn_blockQuoteText, ColorId.bubbleIn_blockQuoteLine ->
      -7495251 // 0xff8da1ad
    ColorId.bubbleOut_blockQuoteText, ColorId.bubbleOut_blockQuoteLine ->
      -5846813 // 0xffa6c8e3
    else -> super.getColor(colorId)
  }
}