@file:JvmName("ThemeBlackWhite")

package io.relimus.flatgram.theme.builtin

import androidx.annotation.ColorInt
import me.vkryl.annotation.Autogenerated
import io.relimus.flatgram.theme.ColorId
import io.relimus.flatgram.theme.ThemeId
import io.relimus.flatgram.theme.PropertyId
import io.relimus.flatgram.theme.ThemeInherited

@Autogenerated class ThemeBlackWhite : ThemeInherited(ThemeId.BLACK_WHITE, ThemeId.NIGHT_BLACK) {
  override fun getProperty (@PropertyId propertyId: Int): Float = when (propertyId) {
    PropertyId.BUBBLE_OUTLINE, PropertyId.REPLACE_SHADOWS_WITH_SEPARATORS ->
      1.0f
    PropertyId.PARENT_THEME ->
      2.0f
    else -> super.getProperty(propertyId)
  }

  @ColorInt override fun getColor (@ColorId colorId: Int): Int = when (colorId) {
    ColorId.badgeFailed, ColorId.headerBadgeFailed ->
      -40864 // 0xffff6060
    ColorId.badgeMuted, ColorId.togglerInactiveBackground, ColorId.headerBadgeMuted ->
      -9408400 // 0xff707070
    ColorId.bubbleOut_waveformActive, ColorId.messageAuthor, ColorId.notification, ColorId.notificationPlayer, ColorId.waveformActive ->
      -1 // 0xffffffff
    ColorId.bubble_chatSeparator, ColorId.bubbleIn_outline, ColorId.bubbleIn_separator, ColorId.bubbleOut_outline, ColorId.chatSeparator, ColorId.inputInactive, ColorId.separator, ColorId.shareSeparator ->
      -14211289 // 0xff272727
    ColorId.bubbleIn_textLink, ColorId.bubbleOut_textLink, ColorId.iv_textLink, ColorId.iv_textMarkedLink, ColorId.textLink ->
      -6250336 // 0xffa0a0a0
    ColorId.bubbleIn_textLinkPressHighlight, ColorId.iv_textLinkPressHighlight, ColorId.textLinkPressHighlight ->
      2007015584 // 0x77a0a0a0
    ColorId.chatListIcon, ColorId.chatListMute ->
      -8947849 // 0xff777777
    ColorId.circleButtonNewChannel, ColorId.circleButtonNewChat, ColorId.circleButtonNewGroup, ColorId.circleButtonNewSecret ->
      -14803426 // 0xff1e1e1e
    ColorId.file, ColorId.fileGreen, ColorId.fileRed, ColorId.fileYellow ->
      -14013910 // 0xff2a2a2a
    ColorId.filling, ColorId.headerLightBackground ->
      -16777216 // 0xff000000
    ColorId.headerBackground, ColorId.passcode ->
      -15724528 // 0xff101010
    ColorId.iconLight ->
      -10790053 // 0xff5b5b5b
    ColorId.messageSelection ->
      452984831 // 0x1affffff
    ColorId.togglerActiveBackground ->
      -4539718 // 0xffbababa
    ColorId.togglerInactive ->
      -7303024 // 0xff909090
    else -> super.getColor(colorId)
  }
}