@file:JvmName("ThemeOrange")

package io.relimus.flatgram.theme.builtin

import androidx.annotation.ColorInt
import me.vkryl.annotation.Autogenerated
import io.relimus.flatgram.theme.ColorId
import io.relimus.flatgram.theme.ColorIdTinted
import io.relimus.flatgram.theme.ThemeId
import io.relimus.flatgram.theme.PropertyId

@Autogenerated class ThemeOrange : ThemeDefault(ThemeId.ORANGE) {
  override fun getProperty (@PropertyId propertyId: Int): Float = when (propertyId) {
    PropertyId.PARENT_THEME ->
      1.0f
    else -> super.getProperty(propertyId)
  }

  @ColorInt override fun getColor (@ColorIdTinted colorId: Int): Int = when (colorId) {
    ColorId.badge, ColorId.bubbleIn_textLink, ColorId.bubbleOut_file, ColorId.bubbleOut_messageAuthor, ColorId.bubbleOut_textLink, ColorId.bubbleOut_ticks, ColorId.bubbleOut_ticksRead, ColorId.chatListAction, ColorId.chatSendButton, ColorId.circleButtonActive, ColorId.circleButtonRegular, ColorId.circleButtonTheme, ColorId.file, ColorId.headerBarCallActive, ColorId.iconActive, ColorId.iv_textLink, ColorId.iv_textMarkedLink, ColorId.messageAuthor, ColorId.online, ColorId.playerButtonActive, ColorId.snackbarUpdate, ColorId.textLink, ColorId.ticks, ColorId.ticksRead, ColorId.togglerActive, ColorId.bubbleOut_fillingPositive, ColorId.bubbleIn_fillingPositive, ColorId.bubbleIn_fillingPositive_overlay, ColorId.bubbleOut_fillingPositive_overlay, ColorId.fillingPositive ->
      -765666 // 0xfff4511e
    ColorId.bubbleIn_progress, ColorId.bubbleOut_inlineOutline, ColorId.bubbleOut_waveformActive, ColorId.checkActive, ColorId.inlineOutline, ColorId.inputActive, ColorId.profileSectionActiveContent, ColorId.progress, ColorId.textNeutral, ColorId.unreadText, ColorId.waveformActive ->
      -43230 // 0xffff5722
    ColorId.bubbleIn_textLinkPressHighlight, ColorId.bubbleOut_textLinkPressHighlight, ColorId.iv_textLinkPressHighlight, ColorId.iv_textMarkedLinkPressHighlight, ColorId.textLinkPressHighlight, ColorId.tooltip_textLinkPressHighlight ->
      1089753374 // 0x40f4511e
    ColorId.bubbleOut_background ->
      -269600 // 0xfffbe2e0
    ColorId.bubbleOut_chatCorrectFilling, ColorId.bubbleOut_chatCorrectChosenFilling, ColorId.bubbleOut_chatVerticalLine, ColorId.chatListVerify, ColorId.controlActive, ColorId.messageSwipeBackground, ColorId.messageVerticalLine, ColorId.promo, ColorId.seekDone, ColorId.sliderActive, ColorId.textSearchQueryHighlight, ColorId.tooltip_textLink, ColorId.avatarArchive, ColorId.avatarSavedMessages, ColorId.avatarSavedMessages_big, ColorId.avatarReplies, ColorId.avatarReplies_big ->
      -36797 // 0xffff7043
    ColorId.bubbleOut_inlineIcon, ColorId.bubbleOut_inlineText, ColorId.inlineIcon, ColorId.inlineText, ColorId.profileSectionActive ->
      -1684967 // 0xffe64a19
    ColorId.bubbleOut_progress, ColorId.bubbleOut_separator, ColorId.bubbleOut_time ->
      -4222847 // 0xffbf9081
    ColorId.bubbleOut_waveformInactive, ColorId.textSelectionHighlight, ColorId.waveformInactive ->
      -13124 // 0xffffccbc
    ColorId.headerBadgeFailed ->
      -11513 // 0xffffd307
    ColorId.headerBackground, ColorId.notification, ColorId.notificationLink, ColorId.notificationPlayer, ColorId.passcode ->
      -2604267 // 0xffd84315
    ColorId.messageSelection ->
      285169442 // 0x10ff5722
    ColorId.seekReady ->
      -9264 // 0xffffdbd0
    ColorId.textNegative ->
      -1754827 // 0xffe53935
    ColorId.togglerActiveBackground ->
      -21615 // 0xffffab91
    ColorId.unread ->
      -267801 // 0xfffbe9e7
    ColorId.bubble_messageSelection, ColorId.bubble_messageSelectionNoWallpaper ->
      872372002 // 0x33ff5722
    ColorId.bubbleOut_fillingActive ->
      653890664 // 0x26f99468
    else -> super.getColor(colorId)
  }
}