@file:JvmName("ThemeClassic")

package io.relimus.flatgram.theme.builtin

import me.vkryl.annotation.Autogenerated
import io.relimus.flatgram.theme.ThemeId
import io.relimus.flatgram.theme.PropertyId

@Autogenerated class ThemeClassic : ThemeBubbleOverride(ThemeId.CLASSIC, ThemeId.GREEN) {
  override fun getProperty (@PropertyId propertyId: Int): Float = when (propertyId) {
    PropertyId.PARENT_THEME ->
      1.0f
    else -> super.getProperty(propertyId)
  }
}