@file:JvmName("ThemeNightBlack")

package io.relimus.flatgram.theme.builtin

import androidx.annotation.ColorInt
import me.vkryl.annotation.Autogenerated
import io.relimus.flatgram.theme.ColorId
import io.relimus.flatgram.theme.ThemeId
import io.relimus.flatgram.theme.PropertyId

@Autogenerated class ThemeNightBlack : ThemeDefault(ThemeId.NIGHT_BLACK) {
  override fun getProperty (@PropertyId propertyId: Int): Float = when (propertyId) {
    PropertyId.DARK, PropertyId.PARENT_THEME, PropertyId.SHADOW_DEPTH, PropertyId.WALLPAPER_USAGE_ID ->
      1.0f
    else -> super.getProperty(propertyId)
  }

  @ColorInt override fun getColor (@ColorId colorId: Int): Int = when (colorId) {
    ColorId.attachContact, ColorId.attachFile, ColorId.attachInlineBot, ColorId.attachLocation, ColorId.attachPhoto, ColorId.badgeMutedText, ColorId.badgeText, ColorId.bubbleIn_background, ColorId.bubbleOut_background, ColorId.chatKeyboardButton, ColorId.headerBackground, ColorId.headerBarCallMuted, ColorId.headerLightBackground, ColorId.inlineContentActive, ColorId.iv_preBlockBackground, ColorId.iv_textCodeBackground, ColorId.iv_textCodeBackgroundPressed, ColorId.messageSwipeBackground, ColorId.notification, ColorId.notificationPlayer, ColorId.passcode, ColorId.unread ->
      -14606047 // 0xff212121
    ColorId.background, ColorId.bubble_chatSeparator, ColorId.bubbleIn_outline, ColorId.bubbleIn_separator, ColorId.bubbleOut_chatCorrectChosenFillingContent, ColorId.bubbleOut_chatCorrectFillingContent, ColorId.bubbleOut_chatNeutralFillingContent, ColorId.bubbleOut_outline, ColorId.chatKeyboard, ColorId.chatSeparator, ColorId.checkContent, ColorId.controlContent, ColorId.iv_chatLinkBackground, ColorId.messageCorrectChosenFillingContent, ColorId.messageCorrectFillingContent, ColorId.messageNegativeLineContent, ColorId.messageNeutralFillingContent, ColorId.promoContent, ColorId.separator, ColorId.shareSeparator, ColorId.togglerPositiveContent, ColorId.circleButtonActiveIcon, ColorId.fillingPositiveContent, ColorId.bubbleOut_fillingPositiveContent, ColorId.bubbleIn_fillingPositiveContent, ColorId.bubbleOut_fillingPositiveContent_overlay, ColorId.bubbleIn_fillingPositiveContent_overlay ->
      -16777216 // 0xff000000
    ColorId.background_icon, ColorId.background_text, ColorId.background_textLight, ColorId.bubbleIn_time, ColorId.bubbleOut_progress, ColorId.bubbleOut_separator, ColorId.bubbleOut_time, ColorId.circleButtonChatIcon, ColorId.circleButtonOverlayIcon, ColorId.icon, ColorId.iv_caption, ColorId.iv_icon, ColorId.iv_pageAuthor, ColorId.iv_pageFooter, ColorId.textLight, ColorId.textPlaceholder, ColorId.blockQuoteText, ColorId.blockQuoteLine, ColorId.bubbleIn_blockQuoteText, ColorId.bubbleIn_blockQuoteLine, ColorId.bubbleOut_blockQuoteText, ColorId.bubbleOut_blockQuoteLine ->
      -6250336 // 0xffa0a0a0
    ColorId.badge, ColorId.bubbleIn_progress, ColorId.bubbleIn_text, ColorId.bubbleOut_chatCorrectChosenFilling, ColorId.bubbleOut_chatCorrectFilling, ColorId.bubbleOut_chatVerticalLine, ColorId.bubbleOut_inlineIcon, ColorId.bubbleOut_inlineOutline, ColorId.bubbleOut_inlineText, ColorId.bubbleOut_text, ColorId.bubbleOut_ticks, ColorId.bubbleOut_ticksRead, ColorId.chatListAction, ColorId.chatListVerify, ColorId.chatSendButton, ColorId.checkActive, ColorId.controlActive, ColorId.headerButtonIcon, ColorId.headerLightIcon, ColorId.headerLightText, ColorId.iconActive, ColorId.inlineIcon, ColorId.inlineOutline, ColorId.inlineText, ColorId.inputActive, ColorId.introSectionActive, ColorId.iv_blockQuoteLine, ColorId.iv_header, ColorId.iv_pageTitle, ColorId.iv_text, ColorId.iv_textCode, ColorId.iv_textMarked, ColorId.iv_textReference, ColorId.messageCorrectChosenFilling, ColorId.messageCorrectFilling, ColorId.messageVerticalLine, ColorId.notificationLink, ColorId.online, ColorId.playerButton, ColorId.profileSectionActive, ColorId.profileSectionActiveContent, ColorId.progress, ColorId.promo, ColorId.sliderActive, ColorId.text, ColorId.textNeutral, ColorId.themeBlackWhite, ColorId.ticks, ColorId.ticksRead, ColorId.togglerActive, ColorId.togglerPositive, ColorId.unreadText, ColorId.headerBadge, ColorId.circleButtonActive, ColorId.bubbleIn_fillingActiveContent, ColorId.bubbleOut_fillingActiveContent, ColorId.fillingActiveContent, ColorId.fillingPositive, ColorId.bubbleOut_fillingPositive, ColorId.bubbleIn_fillingPositive, ColorId.bubbleOut_fillingPositive_overlay, ColorId.bubbleIn_fillingPositive_overlay ->
      -1 // 0xffffffff
    ColorId.badgeMuted, ColorId.controlInactive, ColorId.nameInactive, ColorId.lineInactive, ColorId.themeNightBlack, ColorId.togglerInactiveBackground, ColorId.headerBadgeMuted ->
      -9803158 // 0xff6a6a6a
    ColorId.bubble_button_noWallpaper, ColorId.bubble_buttonRipple_noWallpaper ->
      547397792 // 0x20a0a0a0
    ColorId.bubble_date_noWallpaper, ColorId.bubble_mediaReply_noWallpaper, ColorId.bubble_overlay, ColorId.bubble_unread_noWallpaper ->
      1084268704 // 0x40a0a0a0
    ColorId.bubble_messageCheckOutline ->
      -1381654 // 0xffeaeaea
    ColorId.bubble_messageCheckOutlineNoWallpaper ->
      -9671572 // 0xff6c6c6c
    ColorId.bubble_messageSelection, ColorId.iv_textReferenceOutlinePressed ->
      553648127 // 0x20ffffff
    ColorId.bubble_messageSelectionNoWallpaper ->
      452984831 // 0x1affffff
    ColorId.bubbleIn_pressed, ColorId.bubbleOut_pressed ->
      536870912 // 0x20000000
    ColorId.bubbleIn_textLink, ColorId.bubbleOut_messageAuthor, ColorId.bubbleOut_textLink, ColorId.iv_textLink, ColorId.iv_textMarkedLink, ColorId.messageAuthor, ColorId.textLink, ColorId.textSearchQueryHighlight, ColorId.tooltip_textLink ->
      -8750470 // 0xff7a7a7a
    ColorId.bubbleIn_textLinkPressHighlight, ColorId.bubbleOut_textLinkPressHighlight, ColorId.iv_textLinkPressHighlight, ColorId.iv_textMarkedLinkPressHighlight, ColorId.seekReady, ColorId.textLinkPressHighlight, ColorId.tooltip_textLinkPressHighlight ->
      1081768570 // 0x407a7a7a
    ColorId.bubbleOut_file, ColorId.file, ColorId.fileAttach, ColorId.inputInactive ->
      -12961222 // 0xff3a3a3a
    ColorId.bubbleOut_waveformActive, ColorId.waveformActive ->
      -3487030 // 0xffcacaca
    ColorId.bubbleOut_waveformInactive, ColorId.waveformInactive ->
      -13619152 // 0xff303030
    ColorId.chatBackground, ColorId.filling ->
      -15461356 // 0xff141414
    ColorId.chatListIcon, ColorId.chatListMute ->
      -9341316 // 0xff71767c
    ColorId.circleButtonChat, ColorId.circleButtonOverlay, ColorId.circleButtonRegular, ColorId.circleButtonTheme, ColorId.headerButton, ColorId.overlayFilling, ColorId.seekEmpty ->
      -14803426 // 0xff1e1e1e
    ColorId.fillingPressed ->
      -14671840 // 0xff202020
    ColorId.headerBarCallActive ->
      -12500671 // 0xff414141
    ColorId.headerBarCallIncoming ->
      -8355712 // 0xff808080
    ColorId.headerPlaceholder ->
      285212671 // 0x10ffffff
    ColorId.iconLight ->
      -11248797 // 0xff545b63
    ColorId.introSection ->
      -8289919 // 0xff818181
    ColorId.iv_blockQuote ->
      -197380 // 0xfffcfcfc
    ColorId.iv_pageSubtitle ->
      -4539718 // 0xffbababa
    ColorId.iv_pullQuote ->
      -394759 // 0xfff9f9f9
    ColorId.iv_separator ->
      -12303292 // 0xff444444
    ColorId.iv_textReferenceBackground ->
      720564978 // 0x2af2f2f2
    ColorId.iv_textReferenceBackgroundPressed ->
      820044000 // 0x30e0e0e0
    ColorId.iv_textReferenceOutline, ColorId.tooltip_outline ->
      1157627903 // 0x44ffffff
    ColorId.messageSelection ->
      721420287 // 0x2affffff
    ColorId.notificationSecure, ColorId.textSecure ->
      -8854914 // 0xff78e27e
    ColorId.placeholder ->
      218103807 // 0x0cffffff
    ColorId.playerButtonActive ->
      -3355444 // 0xffcccccc
    ColorId.playerCoverPlaceholder ->
      -15658735 // 0xff111111
    ColorId.previewBackground ->
      1879048192 // 0x70000000
    ColorId.seekDone ->
      -4144960 // 0xffc0c0c0
    ColorId.sliderInactive ->
      -13553359 // 0xff313131
    ColorId.textSelectionHighlight ->
      1442840575 // 0x55ffffff
    ColorId.snackbarUpdate ->
      -13750738 // 0xff2e2e2e
    ColorId.statusBar ->
      1073741824 // 0x40000000
    ColorId.togglerActiveBackground, ColorId.togglerPositiveBackground ->
      -7697782 // 0xff8a8a8a
    ColorId.togglerInactive ->
      -5723992 // 0xffa8a8a8
    ColorId.bubbleIn_fillingActive, ColorId.bubbleOut_fillingActive ->
      -15329770 // 0xff161616
    ColorId.fillingActive ->
      648061088 // 0x26a0a0a0
    ColorId.bubbleOut_messageAuthorPsa, ColorId.messageAuthorPsa ->
      -7551634 // 0xff8cc56e
    ColorId.avatarBlue, ColorId.avatarBlue_big, ColorId.nameBlue ->
      -13202735 // 0xff368ad1
    ColorId.avatarCyan, ColorId.avatarCyan_big, ColorId.nameCyan ->
      -13590854 // 0xff309eba
    ColorId.avatarGreen, ColorId.avatarGreen_big, ColorId.nameGreen ->
      -12539616 // 0xff40a920
    ColorId.avatarOrange, ColorId.avatarOrange_big, ColorId.nameOrange ->
      -2722014 // 0xffd67722
    ColorId.avatarPink, ColorId.avatarPink_big, ColorId.namePink ->
      -3714933 // 0xffc7508b
    ColorId.avatarRed, ColorId.avatarRed_big, ColorId.nameRed ->
      -3387319 // 0xffcc5049
    ColorId.avatarViolet, ColorId.avatarViolet_big ->
      -6988581 // 0xff955cdb
    ColorId.avatarYellow, ColorId.avatarYellow_big, ColorId.nameYellow ->
      -407478 // 0xfff9c84a
    else -> super.getColor(colorId)
  }
}