@file:JvmName("ThemeGreen")

package io.relimus.flatgram.theme.builtin

import androidx.annotation.ColorInt
import me.vkryl.annotation.Autogenerated
import io.relimus.flatgram.theme.ColorId
import io.relimus.flatgram.theme.ColorIdTinted
import io.relimus.flatgram.theme.ThemeId
import io.relimus.flatgram.theme.PropertyId

@Autogenerated class ThemeGreen : ThemeDefault(ThemeId.GREEN) {
  override fun getProperty (@PropertyId propertyId: Int): Float = when (propertyId) {
    PropertyId.PARENT_THEME ->
      1.0f
    else -> super.getProperty(propertyId)
  }

  @ColorInt override fun getColor (@ColorIdTinted colorId: Int): Int = when (colorId) {
    ColorId.badge, ColorId.bubbleIn_textLink, ColorId.bubbleOut_inlineOutline, ColorId.bubbleOut_textLink, ColorId.bubbleOut_ticks, ColorId.bubbleOut_ticksRead, ColorId.bubbleOut_waveformActive, ColorId.chatListAction, ColorId.checkActive, ColorId.iconActive, ColorId.inlineOutline, ColorId.iv_textLink, ColorId.iv_textMarkedLink, ColorId.messageSwipeBackground, ColorId.online, ColorId.profileSectionActiveContent, ColorId.textLink, ColorId.ticks, ColorId.ticksRead, ColorId.togglerActive, ColorId.unreadText, ColorId.waveformActive, ColorId.bubbleOut_fillingPositive, ColorId.bubbleIn_fillingPositive, ColorId.bubbleIn_fillingPositive_overlay, ColorId.bubbleOut_fillingPositive_overlay ->
      -11751600 // 0xff4caf50
    ColorId.bubbleIn_progress, ColorId.bubbleOut_chatCorrectChosenFilling, ColorId.bubbleOut_chatCorrectFilling, ColorId.bubbleOut_chatVerticalLine, ColorId.chatListVerify, ColorId.circleButtonActive, ColorId.circleButtonRegular, ColorId.circleButtonTheme, ColorId.controlActive, ColorId.headerBarCallActive, ColorId.inputActive, ColorId.messageCorrectChosenFilling, ColorId.messageCorrectFilling, ColorId.messageVerticalLine, ColorId.progress, ColorId.seekDone, ColorId.sliderActive, ColorId.snackbarUpdate, ColorId.textNeutral ->
      -10044566 // 0xff66bb6a
    ColorId.bubbleIn_textLinkPressHighlight, ColorId.bubbleOut_textLinkPressHighlight, ColorId.iv_textLinkPressHighlight, ColorId.iv_textMarkedLinkPressHighlight, ColorId.textLinkPressHighlight, ColorId.tooltip_textLinkPressHighlight ->
      1078767440 // 0x404caf50
    ColorId.bubbleOut_background ->
      -1049122 // 0xffeffdde
    ColorId.bubbleOut_file, ColorId.file, ColorId.playerButtonActive ->
      -8862081 // 0xff78c67f
    ColorId.bubbleOut_inlineIcon, ColorId.bubbleOut_inlineText, ColorId.bubbleOut_messageAuthor, ColorId.chatSendButton, ColorId.headerBackground, ColorId.inlineIcon, ColorId.inlineText, ColorId.messageAuthor, ColorId.notification, ColorId.notificationLink, ColorId.notificationPlayer, ColorId.passcode, ColorId.profileSectionActive, ColorId.fillingPositive ->
      -12345273 // 0xff43a047
    ColorId.bubbleOut_outline ->
      -4797475 // 0xffb6cbdd
    ColorId.bubbleOut_progress, ColorId.bubbleOut_separator, ColorId.bubbleOut_time ->
      -9649564 // 0xff6cc264
    ColorId.bubbleOut_waveformInactive, ColorId.textSelectionHighlight, ColorId.waveformInactive ->
      -3610935 // 0xffc8e6c9
    ColorId.messageSelection ->
      275168106 // 0x1066bb6a
    ColorId.promo, ColorId.textSearchQueryHighlight, ColorId.tooltip_textLink, ColorId.avatarArchive, ColorId.avatarSavedMessages, ColorId.avatarSavedMessages_big, ColorId.avatarReplies, ColorId.avatarReplies_big ->
      -8271996 // 0xff81c784
    ColorId.seekReady ->
      -2494758 // 0xffd9eeda
    ColorId.togglerActiveBackground ->
      -5908825 // 0xffa5d6a7
    ColorId.unread ->
      -1509911 // 0xffe8f5e9
    ColorId.bubble_messageSelection, ColorId.bubble_messageSelectionNoWallpaper ->
      860663632 // 0x334caf50
    ColorId.bubbleOut_fillingActive ->
      748145474 // 0x2c97cb42
    else -> super.getColor(colorId)
  }
}