/*
 * This file is a part of Telegram X
 * Copyright © 2014 (tgx-android@pm.me)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * File initially created on 08/07/2017
 *
 * AUTOGENERATED. DO NOT MODIFY
 */
package io.relimus.flatgram.theme;

import androidx.annotation.IntDef;

import io.relimus.flatgram.R;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

import me.vkryl.annotation.Autogenerated;

@Autogenerated
@Retention(RetentionPolicy.SOURCE)
@IntDef({
  ColorId.NONE,
  ColorId.snackbarUpdate,
  ColorId.fillingPositive,
  ColorId.tooltip_textLink,
  ColorId.tooltip_textLinkPressHighlight,
  ColorId.textSelectionHighlight,
  ColorId.textNeutral,
  ColorId.textLink,
  ColorId.textLinkPressHighlight,
  ColorId.textSearchQueryHighlight,
  ColorId.iconActive,
  ColorId.progress,
  ColorId.controlActive,
  ColorId.checkActive,
  ColorId.sliderActive,
  ColorId.togglerActive,
  ColorId.togglerActiveBackground,
  ColorId.inputActive,
  ColorId.inlineOutline,
  ColorId.inlineText,
  ColorId.inlineIcon,
  ColorId.circleButtonRegular,
  ColorId.circleButtonActive,
  ColorId.circleButtonTheme,
  ColorId.seekReady,
  ColorId.seekDone,
  ColorId.playerButtonActive,
  ColorId.online,
  ColorId.promo,
  ColorId.profileSectionActive,
  ColorId.profileSectionActiveContent,
  ColorId.avatarArchive,
  ColorId.avatarSavedMessages,
  ColorId.avatarSavedMessages_big,
  ColorId.avatarReplies,
  ColorId.avatarReplies_big,
  ColorId.headerBackground,
  ColorId.headerBarCallActive,
  ColorId.passcode,
  ColorId.notification,
  ColorId.notificationLink,
  ColorId.notificationPlayer,
  ColorId.ticks,
  ColorId.ticksRead,
  ColorId.chatListAction,
  ColorId.chatListVerify,
  ColorId.badge,
  ColorId.chatSendButton,
  ColorId.unread,
  ColorId.unreadText,
  ColorId.messageVerticalLine,
  ColorId.messageSelection,
  ColorId.messageSwipeBackground,
  ColorId.messageAuthor,
  ColorId.bubble_messageSelection,
  ColorId.bubble_messageSelectionNoWallpaper,
  ColorId.bubbleIn_progress,
  ColorId.bubbleIn_textLink,
  ColorId.bubbleIn_textLinkPressHighlight,
  ColorId.bubbleIn_fillingPositive,
  ColorId.bubbleIn_fillingPositive_overlay,
  ColorId.bubbleOut_background,
  ColorId.bubbleOut_time,
  ColorId.bubbleOut_progress,
  ColorId.bubbleOut_textLink,
  ColorId.bubbleOut_textLinkPressHighlight,
  ColorId.bubbleOut_separator,
  ColorId.bubbleOut_chatVerticalLine,
  ColorId.bubbleOut_chatCorrectFilling,
  ColorId.bubbleOut_chatCorrectChosenFilling,
  ColorId.bubbleOut_inlineText,
  ColorId.bubbleOut_inlineOutline,
  ColorId.bubbleOut_inlineIcon,
  ColorId.bubbleOut_waveformActive,
  ColorId.bubbleOut_waveformInactive,
  ColorId.bubbleOut_file,
  ColorId.bubbleOut_ticks,
  ColorId.bubbleOut_ticksRead,
  ColorId.bubbleOut_messageAuthor,
  ColorId.bubbleOut_fillingPositive,
  ColorId.bubbleOut_fillingPositive_overlay,
  ColorId.file,
  ColorId.waveformActive,
  ColorId.waveformInactive,
  ColorId.iv_textMarkedLink,
  ColorId.iv_textMarkedLinkPressHighlight,
  ColorId.iv_textLink,
  ColorId.iv_textLinkPressHighlight
})
public @interface ColorIdTinted { }