/*
 * This file is a part of Telegram X
 * Copyright © 2014 (tgx-android@pm.me)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * File initially created on 25/12/2020
 *
 * AUTOGENERATED. DO NOT MODIFY
 */
package io.relimus.flatgram.theme;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

import me.vkryl.annotation.Autogenerated;

@Autogenerated
@Retention(RetentionPolicy.SOURCE)
@IntDef({
  ColorId.NONE,
  ColorId.background,
  ColorId.fillingPositiveContent,
  ColorId.tooltip_text,
  ColorId.text,
  ColorId.textLight,
  ColorId.textSecure,
  ColorId.textNeutral,
  ColorId.textNegative,
  ColorId.textLink,
  ColorId.textSearchQueryHighlight,
  ColorId.background_icon,
  ColorId.icon,
  ColorId.iconActive,
  ColorId.iconLight,
  ColorId.iconPositive,
  ColorId.iconNegative,
  ColorId.inlineText,
  ColorId.inlineIcon,
  ColorId.circleButtonChatIcon,
  ColorId.playerCoverIcon,
  ColorId.avatar_content,
  ColorId.nameInactive,
  ColorId.nameRed,
  ColorId.nameOrange,
  ColorId.nameYellow,
  ColorId.nameGreen,
  ColorId.nameCyan,
  ColorId.nameBlue,
  ColorId.nameViolet,
  ColorId.namePink,
  ColorId.lineInactive,
  ColorId.lineRed,
  ColorId.lineOrange,
  ColorId.lineYellow,
  ColorId.lineGreen,
  ColorId.lineCyan,
  ColorId.lineBlue,
  ColorId.lineViolet,
  ColorId.linePink,
  ColorId.headerText,
  ColorId.headerIcon,
  ColorId.headerButtonIcon,
  ColorId.passcodeIcon,
  ColorId.passcodeText,
  ColorId.ticks,
  ColorId.ticksRead,
  ColorId.chatListMute,
  ColorId.chatListIcon,
  ColorId.chatListVerify,
  ColorId.badgeText,
  ColorId.badgeFailedText,
  ColorId.badgeMuted,
  ColorId.badgeMutedText,
  ColorId.chatSendButton,
  ColorId.messageAuthor,
  ColorId.bubble_mediaTimeText,
  ColorId.bubble_mediaTimeText_noWallpaper,
  ColorId.bubble_mediaOverlayText,
  ColorId.bubbleIn_time,
  ColorId.bubbleOut_time,
  ColorId.bubbleOut_inlineIcon,
  ColorId.bubbleOut_waveformActive,
  ColorId.bubbleOut_file,
  ColorId.bubbleOut_fileContent,
  ColorId.bubbleOut_ticks,
  ColorId.bubbleOut_ticksRead,
  ColorId.bubbleOut_messageAuthor,
  ColorId.file,
  ColorId.fileContent,
  ColorId.waveformActive,
  ColorId.waveformInactive,
  ColorId.white,
  ColorId.blockQuoteText,
  ColorId.blockQuoteLine,
  ColorId.bubbleIn_blockQuoteText,
  ColorId.bubbleIn_blockQuoteLine,
  ColorId.bubbleOut_blockQuoteText,
  ColorId.bubbleOut_blockQuoteLine
})
public @interface PorterDuffColorId { }