/*
 * This file is a part of Telegram X
 * Copyright © 2014 (tgx-android@pm.me)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * File initially created on 04/11/2018
 *
 * AUTOGENERATED. DO NOT MODIFY
 */
package io.relimus.flatgram.theme;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

import me.vkryl.annotation.Autogenerated;

@Autogenerated
@Retention(RetentionPolicy.SOURCE)
@IntDef({
  PropertyId.NONE,
  PropertyId.PARENT_THEME,
  PropertyId.WALLPAPER_ID,
  PropertyId.DARK,
  PropertyId.IMAGE_CORNER,
  PropertyId.REPLACE_SHADOWS_WITH_SEPARATORS,
  PropertyId.BUBBLE_CORNER_MERGED,
  PropertyId.BUBBLE_CORNER,
  PropertyId.BUBBLE_CORNER_LEGACY,
  PropertyId.BUBBLE_OUTER_MARGIN,
  PropertyId.BUBBLE_OUTLINE,
  PropertyId.BUBBLE_OUTLINE_SIZE,
  PropertyId.BUBBLE_UNREAD_SHADOW,
  PropertyId.BUBBLE_DATE_CORNER,
  PropertyId.DATE_CORNER,
  PropertyId.WALLPAPER_USAGE_ID,
  PropertyId.SHADOW_DEPTH,
  PropertyId.SUBTITLE_ALPHA,
  PropertyId.LIGHT_STATUS_BAR,
  PropertyId.AVATAR_RADIUS,
  PropertyId.AVATAR_RADIUS_FORUM,
  PropertyId.AVATAR_RADIUS_CHAT_LIST,
  PropertyId.AVATAR_RADIUS_CHAT_LIST_FORUM,
  PropertyId.WALLPAPER_OVERRIDE_DATE,
  PropertyId.WALLPAPER_OVERRIDE_UNREAD,
  PropertyId.WALLPAPER_OVERRIDE_MEDIA_REPLY,
  PropertyId.WALLPAPER_OVERRIDE_TIME,
  PropertyId.WALLPAPER_OVERRIDE_BUTTON,
  PropertyId.WALLPAPER_OVERRIDE_OVERLAY
})
public @interface PropertyId {
  int
    NONE = 0,
    PARENT_THEME = 1,
    WALLPAPER_ID = 2,
    DARK = 3,
    IMAGE_CORNER = 4,
    REPLACE_SHADOWS_WITH_SEPARATORS = 5,
    BUBBLE_CORNER_MERGED = 6,
    BUBBLE_CORNER = 7,
    BUBBLE_CORNER_LEGACY = 8,
    BUBBLE_OUTER_MARGIN = 9,
    BUBBLE_OUTLINE = 10,
    BUBBLE_OUTLINE_SIZE = 11,
    BUBBLE_UNREAD_SHADOW = 12,
    BUBBLE_DATE_CORNER = 13,
    DATE_CORNER = 14,
    WALLPAPER_USAGE_ID = 15,
    SHADOW_DEPTH = 16,
    SUBTITLE_ALPHA = 17,
    LIGHT_STATUS_BAR = 18,
    AVATAR_RADIUS = 19,
    AVATAR_RADIUS_FORUM = 20,
    AVATAR_RADIUS_CHAT_LIST = 21,
    AVATAR_RADIUS_CHAT_LIST_FORUM = 22,
    WALLPAPER_OVERRIDE_DATE = 23,
    WALLPAPER_OVERRIDE_UNREAD = 24,
    WALLPAPER_OVERRIDE_MEDIA_REPLY = 25,
    WALLPAPER_OVERRIDE_TIME = 26,
    WALLPAPER_OVERRIDE_BUTTON = 27,
    WALLPAPER_OVERRIDE_OVERLAY = 28;
}