@file:JvmName("ThemeProperties")

package io.relimus.flatgram.theme

import me.vkryl.annotation.Autogenerated

@Autogenerated class ThemeProperties {
  private var parentTheme: Float? = null
  private var wallpaperId: Float? = null
  private var dark: Float? = null
  private var imageCorner: Float? = null
  private var replaceShadowsWithSeparators: Float? = null
  private var bubbleCornerMerged: Float? = null
  private var bubbleCorner: Float? = null
  private var bubbleCornerLegacy: Float? = null
  private var bubbleOuterMargin: Float? = null
  private var bubbleOutline: Float? = null
  private var bubbleOutlineSize: Float? = null
  private var bubbleUnreadShadow: Float? = null
  private var bubbleDateCorner: Float? = null
  private var dateCorner: Float? = null
  private var wallpaperUsageId: Float? = null
  private var shadowDepth: Float? = null
  private var subtitleAlpha: Float? = null
  private var lightStatusBar: Float? = null
  private var avatarRadius: Float? = null
  private var avatarRadiusForum: Float? = null
  private var avatarRadiusChatList: Float? = null
  private var avatarRadiusChatListForum: Float? = null
  private var wallpaperOverrideDate: Float? = null
  private var wallpaperOverrideUnread: Float? = null
  private var wallpaperOverrideMediaReply: Float? = null
  private var wallpaperOverrideTime: Float? = null
  private var wallpaperOverrideButton: Float? = null
  private var wallpaperOverrideOverlay: Float? = null
  
  constructor ()
  constructor (copy: ThemeProperties) {
    this.parentTheme = copy.parentTheme
    this.wallpaperId = copy.wallpaperId
    this.dark = copy.dark
    this.imageCorner = copy.imageCorner
    this.replaceShadowsWithSeparators = copy.replaceShadowsWithSeparators
    this.bubbleCornerMerged = copy.bubbleCornerMerged
    this.bubbleCorner = copy.bubbleCorner
    this.bubbleCornerLegacy = copy.bubbleCornerLegacy
    this.bubbleOuterMargin = copy.bubbleOuterMargin
    this.bubbleOutline = copy.bubbleOutline
    this.bubbleOutlineSize = copy.bubbleOutlineSize
    this.bubbleUnreadShadow = copy.bubbleUnreadShadow
    this.bubbleDateCorner = copy.bubbleDateCorner
    this.dateCorner = copy.dateCorner
    this.wallpaperUsageId = copy.wallpaperUsageId
    this.shadowDepth = copy.shadowDepth
    this.subtitleAlpha = copy.subtitleAlpha
    this.lightStatusBar = copy.lightStatusBar
    this.avatarRadius = copy.avatarRadius
    this.avatarRadiusForum = copy.avatarRadiusForum
    this.avatarRadiusChatList = copy.avatarRadiusChatList
    this.avatarRadiusChatListForum = copy.avatarRadiusChatListForum
    this.wallpaperOverrideDate = copy.wallpaperOverrideDate
    this.wallpaperOverrideUnread = copy.wallpaperOverrideUnread
    this.wallpaperOverrideMediaReply = copy.wallpaperOverrideMediaReply
    this.wallpaperOverrideTime = copy.wallpaperOverrideTime
    this.wallpaperOverrideButton = copy.wallpaperOverrideButton
    this.wallpaperOverrideOverlay = copy.wallpaperOverrideOverlay
  }

  fun get (@PropertyId propertyId: Int): Float? = when (propertyId) {
    PropertyId.PARENT_THEME -> this.parentTheme
    PropertyId.WALLPAPER_ID -> this.wallpaperId
    PropertyId.DARK -> this.dark
    PropertyId.IMAGE_CORNER -> this.imageCorner
    PropertyId.REPLACE_SHADOWS_WITH_SEPARATORS -> this.replaceShadowsWithSeparators
    PropertyId.BUBBLE_CORNER_MERGED -> this.bubbleCornerMerged
    PropertyId.BUBBLE_CORNER -> this.bubbleCorner
    PropertyId.BUBBLE_CORNER_LEGACY -> this.bubbleCornerLegacy
    PropertyId.BUBBLE_OUTER_MARGIN -> this.bubbleOuterMargin
    PropertyId.BUBBLE_OUTLINE -> this.bubbleOutline
    PropertyId.BUBBLE_OUTLINE_SIZE -> this.bubbleOutlineSize
    PropertyId.BUBBLE_UNREAD_SHADOW -> this.bubbleUnreadShadow
    PropertyId.BUBBLE_DATE_CORNER -> this.bubbleDateCorner
    PropertyId.DATE_CORNER -> this.dateCorner
    PropertyId.WALLPAPER_USAGE_ID -> this.wallpaperUsageId
    PropertyId.SHADOW_DEPTH -> this.shadowDepth
    PropertyId.SUBTITLE_ALPHA -> this.subtitleAlpha
    PropertyId.LIGHT_STATUS_BAR -> this.lightStatusBar
    PropertyId.AVATAR_RADIUS -> this.avatarRadius
    PropertyId.AVATAR_RADIUS_FORUM -> this.avatarRadiusForum
    PropertyId.AVATAR_RADIUS_CHAT_LIST -> this.avatarRadiusChatList
    PropertyId.AVATAR_RADIUS_CHAT_LIST_FORUM -> this.avatarRadiusChatListForum
    PropertyId.WALLPAPER_OVERRIDE_DATE -> this.wallpaperOverrideDate
    PropertyId.WALLPAPER_OVERRIDE_UNREAD -> this.wallpaperOverrideUnread
    PropertyId.WALLPAPER_OVERRIDE_MEDIA_REPLY -> this.wallpaperOverrideMediaReply
    PropertyId.WALLPAPER_OVERRIDE_TIME -> this.wallpaperOverrideTime
    PropertyId.WALLPAPER_OVERRIDE_BUTTON -> this.wallpaperOverrideButton
    PropertyId.WALLPAPER_OVERRIDE_OVERLAY -> this.wallpaperOverrideOverlay
    else -> throw Theme.newError(propertyId, "propertyId")
  }

  fun set (@PropertyId propertyId: Int, value: Float?) = when (propertyId) {
    PropertyId.PARENT_THEME -> this.parentTheme = value
    PropertyId.WALLPAPER_ID -> this.wallpaperId = value
    PropertyId.DARK -> this.dark = value
    PropertyId.IMAGE_CORNER -> this.imageCorner = value
    PropertyId.REPLACE_SHADOWS_WITH_SEPARATORS -> this.replaceShadowsWithSeparators = value
    PropertyId.BUBBLE_CORNER_MERGED -> this.bubbleCornerMerged = value
    PropertyId.BUBBLE_CORNER -> this.bubbleCorner = value
    PropertyId.BUBBLE_CORNER_LEGACY -> this.bubbleCornerLegacy = value
    PropertyId.BUBBLE_OUTER_MARGIN -> this.bubbleOuterMargin = value
    PropertyId.BUBBLE_OUTLINE -> this.bubbleOutline = value
    PropertyId.BUBBLE_OUTLINE_SIZE -> this.bubbleOutlineSize = value
    PropertyId.BUBBLE_UNREAD_SHADOW -> this.bubbleUnreadShadow = value
    PropertyId.BUBBLE_DATE_CORNER -> this.bubbleDateCorner = value
    PropertyId.DATE_CORNER -> this.dateCorner = value
    PropertyId.WALLPAPER_USAGE_ID -> this.wallpaperUsageId = value
    PropertyId.SHADOW_DEPTH -> this.shadowDepth = value
    PropertyId.SUBTITLE_ALPHA -> this.subtitleAlpha = value
    PropertyId.LIGHT_STATUS_BAR -> this.lightStatusBar = value
    PropertyId.AVATAR_RADIUS -> this.avatarRadius = value
    PropertyId.AVATAR_RADIUS_FORUM -> this.avatarRadiusForum = value
    PropertyId.AVATAR_RADIUS_CHAT_LIST -> this.avatarRadiusChatList = value
    PropertyId.AVATAR_RADIUS_CHAT_LIST_FORUM -> this.avatarRadiusChatListForum = value
    PropertyId.WALLPAPER_OVERRIDE_DATE -> this.wallpaperOverrideDate = value
    PropertyId.WALLPAPER_OVERRIDE_UNREAD -> this.wallpaperOverrideUnread = value
    PropertyId.WALLPAPER_OVERRIDE_MEDIA_REPLY -> this.wallpaperOverrideMediaReply = value
    PropertyId.WALLPAPER_OVERRIDE_TIME -> this.wallpaperOverrideTime = value
    PropertyId.WALLPAPER_OVERRIDE_BUTTON -> this.wallpaperOverrideButton = value
    PropertyId.WALLPAPER_OVERRIDE_OVERLAY -> this.wallpaperOverrideOverlay = value
    else -> throw Theme.newError(propertyId, "propertyId")
  }
  
  companion object {
    const val COUNT = 28

    @JvmStatic fun getAll (): Array<Int> = arrayOf(
      PropertyId.PARENT_THEME,
      PropertyId.WALLPAPER_ID,
      PropertyId.DARK,
      PropertyId.IMAGE_CORNER,
      PropertyId.REPLACE_SHADOWS_WITH_SEPARATORS,
      PropertyId.BUBBLE_CORNER_MERGED,
      PropertyId.BUBBLE_CORNER,
      PropertyId.BUBBLE_CORNER_LEGACY,
      PropertyId.BUBBLE_OUTER_MARGIN,
      PropertyId.BUBBLE_OUTLINE,
      PropertyId.BUBBLE_OUTLINE_SIZE,
      PropertyId.BUBBLE_UNREAD_SHADOW,
      PropertyId.BUBBLE_DATE_CORNER,
      PropertyId.DATE_CORNER,
      PropertyId.WALLPAPER_USAGE_ID,
      PropertyId.SHADOW_DEPTH,
      PropertyId.SUBTITLE_ALPHA,
      PropertyId.LIGHT_STATUS_BAR,
      PropertyId.AVATAR_RADIUS,
      PropertyId.AVATAR_RADIUS_FORUM,
      PropertyId.AVATAR_RADIUS_CHAT_LIST,
      PropertyId.AVATAR_RADIUS_CHAT_LIST_FORUM,
      PropertyId.WALLPAPER_OVERRIDE_DATE,
      PropertyId.WALLPAPER_OVERRIDE_UNREAD,
      PropertyId.WALLPAPER_OVERRIDE_MEDIA_REPLY,
      PropertyId.WALLPAPER_OVERRIDE_TIME,
      PropertyId.WALLPAPER_OVERRIDE_BUTTON,
      PropertyId.WALLPAPER_OVERRIDE_OVERLAY
    )

    @JvmStatic fun getMap (): Map<String, Int> = mapOf(
      Pair("parentTheme", PropertyId.PARENT_THEME),
      Pair("wallpaperId", PropertyId.WALLPAPER_ID),
      Pair("dark", PropertyId.DARK),
      Pair("imageCorner", PropertyId.IMAGE_CORNER),
      Pair("replaceShadowsWithSeparators", PropertyId.REPLACE_SHADOWS_WITH_SEPARATORS),
      Pair("bubbleCornerMerged", PropertyId.BUBBLE_CORNER_MERGED),
      Pair("bubbleCorner", PropertyId.BUBBLE_CORNER),
      Pair("bubbleCornerLegacy", PropertyId.BUBBLE_CORNER_LEGACY),
      Pair("bubbleOuterMargin", PropertyId.BUBBLE_OUTER_MARGIN),
      Pair("bubbleOutline", PropertyId.BUBBLE_OUTLINE),
      Pair("bubbleOutlineSize", PropertyId.BUBBLE_OUTLINE_SIZE),
      Pair("bubbleUnreadShadow", PropertyId.BUBBLE_UNREAD_SHADOW),
      Pair("bubbleDateCorner", PropertyId.BUBBLE_DATE_CORNER),
      Pair("dateCorner", PropertyId.DATE_CORNER),
      Pair("wallpaperUsageId", PropertyId.WALLPAPER_USAGE_ID),
      Pair("shadowDepth", PropertyId.SHADOW_DEPTH),
      Pair("subtitleAlpha", PropertyId.SUBTITLE_ALPHA),
      Pair("lightStatusBar", PropertyId.LIGHT_STATUS_BAR),
      Pair("avatarRadius", PropertyId.AVATAR_RADIUS),
      Pair("avatarRadiusForum", PropertyId.AVATAR_RADIUS_FORUM),
      Pair("avatarRadiusChatList", PropertyId.AVATAR_RADIUS_CHAT_LIST),
      Pair("avatarRadiusChatListForum", PropertyId.AVATAR_RADIUS_CHAT_LIST_FORUM),
      Pair("wallpaperOverrideDate", PropertyId.WALLPAPER_OVERRIDE_DATE),
      Pair("wallpaperOverrideUnread", PropertyId.WALLPAPER_OVERRIDE_UNREAD),
      Pair("wallpaperOverrideMediaReply", PropertyId.WALLPAPER_OVERRIDE_MEDIA_REPLY),
      Pair("wallpaperOverrideTime", PropertyId.WALLPAPER_OVERRIDE_TIME),
      Pair("wallpaperOverrideButton", PropertyId.WALLPAPER_OVERRIDE_BUTTON),
      Pair("wallpaperOverrideOverlay", PropertyId.WALLPAPER_OVERRIDE_OVERLAY)
    )

    @JvmStatic fun getName (@PropertyId propertyId: Int): String = when (propertyId) {
      PropertyId.PARENT_THEME -> "parentTheme"
      PropertyId.WALLPAPER_ID -> "wallpaperId"
      PropertyId.DARK -> "dark"
      PropertyId.IMAGE_CORNER -> "imageCorner"
      PropertyId.REPLACE_SHADOWS_WITH_SEPARATORS -> "replaceShadowsWithSeparators"
      PropertyId.BUBBLE_CORNER_MERGED -> "bubbleCornerMerged"
      PropertyId.BUBBLE_CORNER -> "bubbleCorner"
      PropertyId.BUBBLE_CORNER_LEGACY -> "bubbleCornerLegacy"
      PropertyId.BUBBLE_OUTER_MARGIN -> "bubbleOuterMargin"
      PropertyId.BUBBLE_OUTLINE -> "bubbleOutline"
      PropertyId.BUBBLE_OUTLINE_SIZE -> "bubbleOutlineSize"
      PropertyId.BUBBLE_UNREAD_SHADOW -> "bubbleUnreadShadow"
      PropertyId.BUBBLE_DATE_CORNER -> "bubbleDateCorner"
      PropertyId.DATE_CORNER -> "dateCorner"
      PropertyId.WALLPAPER_USAGE_ID -> "wallpaperUsageId"
      PropertyId.SHADOW_DEPTH -> "shadowDepth"
      PropertyId.SUBTITLE_ALPHA -> "subtitleAlpha"
      PropertyId.LIGHT_STATUS_BAR -> "lightStatusBar"
      PropertyId.AVATAR_RADIUS -> "avatarRadius"
      PropertyId.AVATAR_RADIUS_FORUM -> "avatarRadiusForum"
      PropertyId.AVATAR_RADIUS_CHAT_LIST -> "avatarRadiusChatList"
      PropertyId.AVATAR_RADIUS_CHAT_LIST_FORUM -> "avatarRadiusChatListForum"
      PropertyId.WALLPAPER_OVERRIDE_DATE -> "wallpaperOverrideDate"
      PropertyId.WALLPAPER_OVERRIDE_UNREAD -> "wallpaperOverrideUnread"
      PropertyId.WALLPAPER_OVERRIDE_MEDIA_REPLY -> "wallpaperOverrideMediaReply"
      PropertyId.WALLPAPER_OVERRIDE_TIME -> "wallpaperOverrideTime"
      PropertyId.WALLPAPER_OVERRIDE_BUTTON -> "wallpaperOverrideButton"
      PropertyId.WALLPAPER_OVERRIDE_OVERLAY -> "wallpaperOverrideOverlay"
      else -> throw Theme.newError(propertyId, "propertyId")
    }
  }
}